---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:80']

alertmanager:
  enabled: false        # Deshabilitar Alertmanager si no lo necesitas

pushgateway:
  enabled: false        # Deshabilitar Pushgateway si no lo necesitas

server:
  persistentVolume:
    enabled: false      # Deshabilitar almacenamiento persistente si no lo necesitas
  service:
    type: LoadBalancer  # Exponer Prometheus públicamente
    port: 80


