---
server:
  ## Prometheus server container name
  ##
  name: server

  ## namespaces to monitor (instead of monitoring all - clusterwide). Needed if you want to run without Cluster-admin privileges.
  namespaces:
    - prometheus

  image:
    repository: quay.io/prometheus/prometheus
    # if not set appVersion field from Chart.yaml is used
    tag: ""
    # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
    digest: ""
    pullPolicy: IfNotPresent

  enableServiceLinks: true

  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m

  strategy:
    type: Recreate

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    #mountPath: /data
    size: 10Gi
    storageClass: "gp2"

  replicaCount: 1
  # When hostNetwork is enabled, this will set to ClusterFirstWithHostNet automatically
  dnsPolicy: ClusterFirst

  service:
    enabled: true
    servicePort: 80
    type: ClusterIP

  retention: "15d"
